# -*- coding: utf-8 -*-
"""final_gfp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-0rIxHP0hdwZLPcXpzBy-FkwsKW15-kI
"""

# ============================================================
# GeneMeow final submission from uploaded ColabFold RESULTS archive
# memory-safe version
# ============================================================
#
# Что делает скрипт:
# 1. Загружает zip-архив с результатами ColabFold.
# 2. Опционально загружает top24_for_colabfold_v2.csv, если вы его добавите вместе с архивом.
# 3. Распаковывает архив.
# 4. Находит rank_001 JSON/PDB/A3M.
# 5. Считает ColabFold-метрики.
# 6. Выбирает финальные 6 GeneMeow-кандидатов.
# 7. Создаёт submission_GeneMeow.csv с колонками:
#    Team_Name, Seq_ID, Sequence
# 8. Создаёт summary-таблицу.
# 9. Создаёт графики.
# 10. Скачивает только нужные файлы, НЕ архивируя всю тяжёлую папку результатов.
#
# ВАЖНО:
# Загружать нужно архив результатов ColabFold, а не архив входных FASTA.
# То есть нужен архив, внутри которого есть rank_001 .json/.pdb файлы.
# ============================================================

import os
import re
import glob
import json
import shutil
import zipfile
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

try:
    from google.colab import files
    IN_COLAB = True
except Exception:
    IN_COLAB = False


# ============================================================
# 1. Settings
# ============================================================

TEAM_NAME = "GeneMeow"

OUTPUT_DIR = "/content/GeneMeow_final_submission_outputs"
EXTRACT_DIR = os.path.join(OUTPUT_DIR, "uploaded_colabfold_results_extracted")
FIGURES_DIR = os.path.join(OUTPUT_DIR, "figures")
RAW_COLABFOLD_FIGURES_DIR = os.path.join(FIGURES_DIR, "colabfold_raw_plots_final6")

MINIMAL_PACKAGE_DIR = "/content/GeneMeow_minimal_submission_package"

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(EXTRACT_DIR, exist_ok=True)
os.makedirs(FIGURES_DIR, exist_ok=True)
os.makedirs(RAW_COLABFOLD_FIGURES_DIR, exist_ok=True)
os.makedirs(MINIMAL_PACKAGE_DIR, exist_ok=True)

ALLOWED_AA = set("ACDEFGHIKLMNPQRSTVWY")

CHROMOPHORE_POSITIONS = [65, 66, 67]
CORE_START = 1
CORE_END = 220

FINAL_QUERY_ORDER = [
    {
        "Seq_ID": 1,
        "ColabFold_Query_ID": "Query_02_CANDV2_01071",
        "Recommended_Role": "conservative low-risk H148S + mild charge",
        "Mutations": "L220V:H148S:K156E:N164Y",
        "Design_Family": "conservative_H148S_mild_charge"
    },
    {
        "Seq_ID": 2,
        "ColabFold_Query_ID": "Query_06_CANDV2_06745",
        "Recommended_Role": "balanced medium-charge main candidate",
        "Mutations": "L220V:H148S:K101E:K156E:N164Y",
        "Design_Family": "balanced_H148S_medium_charge"
    },
    {
        "Seq_ID": 3,
        "ColabFold_Query_ID": "Query_15_CANDV2_26898",
        "Recommended_Role": "best overall computational candidate",
        "Mutations": "L220V:H148S:K156E:K166E:K214E:N164Y",
        "Design_Family": "balanced_H148S_stronger_charge"
    },
    {
        "Seq_ID": 4,
        "ColabFold_Query_ID": "Query_16_CANDV2_26760",
        "Recommended_Role": "balanced alternative with N198D",
        "Mutations": "L220V:H148S:N198D:K101E:K156E:N164Y",
        "Design_Family": "balanced_H148S_stronger_charge"
    },
    {
        "Seq_ID": 5,
        "ColabFold_Query_ID": "Query_18_CANDV2_77117",
        "Recommended_Role": "thermal-retention supercharged bet",
        "Mutations": "L220V:H148S:K101E:K156E:K166E:K214E:N164Y",
        "Design_Family": "thermal_supercharged_H148S"
    },
    {
        "Seq_ID": 6,
        "ColabFold_Query_ID": "Query_24_CANDV2_26657",
        "Recommended_Role": "backup without H148S",
        "Mutations": "L220V:Q183R:K101E:K166E:K214E:N164Y",
        "Design_Family": "backup_without_H148S"
    }
]


# ============================================================
# 2. Upload files
# ============================================================

print("Загрузите zip-архив с РЕЗУЛЬТАТАМИ ColabFold.")
print("Можно загрузить вместе с ним top24_for_colabfold_v2.csv.")
print("Архив должен содержать rank_001 .json/.pdb файлы.")

if not IN_COLAB:
    raise RuntimeError("Этот скрипт рассчитан на Google Colab.")

uploaded = files.upload()

uploaded_paths = []

for uploaded_name in uploaded.keys():
    src = f"/content/{uploaded_name}"
    uploaded_paths.append(src)

print("\nUploaded files:")
for path in uploaded_paths:
    print(path)

zip_files = [path for path in uploaded_paths if path.lower().endswith(".zip")]
csv_files = [path for path in uploaded_paths if path.lower().endswith(".csv")]

if len(zip_files) == 0:
    raise FileNotFoundError("Zip-архив не найден. Нужно загрузить архив результатов ColabFold.")

zip_files = sorted(zip_files, key=lambda p: os.path.getsize(p), reverse=True)
COLABFOLD_RESULTS_ZIP = zip_files[0]

print("\nSelected ColabFold results archive:")
print(COLABFOLD_RESULTS_ZIP)

top24_csv_path = None

for path in csv_files:
    if os.path.basename(path) == "top24_for_colabfold_v2.csv":
        top24_csv_path = path
        break

if top24_csv_path is None:
    for path in csv_files:
        if "top24" in os.path.basename(path).lower():
            top24_csv_path = path
            break

if top24_csv_path is not None:
    print("\nOptional top24 table found:")
    print(top24_csv_path)
else:
    print("\nNo top24_for_colabfold_v2.csv uploaded.")
    print("The script will extract sequences from A3M/PDB, but metadata columns may be incomplete.")


# ============================================================
# 3. Helper functions
# ============================================================

def normalize_sequence(seq):
    seq = str(seq)
    seq = re.sub(r"\s+", "", seq)
    seq = seq.upper()
    return seq


def validate_submission_sequence(seq_id, sequence):
    sequence = normalize_sequence(sequence)
    errors = []

    if not sequence.startswith("M"):
        errors.append("does not start with M")

    if len(sequence) < 220 or len(sequence) > 250:
        errors.append(f"length is {len(sequence)}, expected 220-250 aa")

    invalid = sorted(set(sequence) - ALLOWED_AA)
    if invalid:
        errors.append("invalid characters: " + "".join(invalid))

    if errors:
        raise ValueError(f"Seq_ID {seq_id}: " + "; ".join(errors))

    return sequence


def recursively_extract_zip(zip_path, extract_to):
    os.makedirs(extract_to, exist_ok=True)

    with zipfile.ZipFile(zip_path, "r") as zip_ref:
        zip_ref.extractall(extract_to)

    nested_zip_files = glob.glob(os.path.join(extract_to, "**", "*.zip"), recursive=True)

    for nested_zip in nested_zip_files:
        nested_name = os.path.splitext(os.path.basename(nested_zip))[0]
        nested_dir = os.path.join(os.path.dirname(nested_zip), nested_name + "_extracted")
        os.makedirs(nested_dir, exist_ok=True)

        try:
            with zipfile.ZipFile(nested_zip, "r") as nested_ref:
                nested_ref.extractall(nested_dir)
        except zipfile.BadZipFile:
            pass


def extract_query_id_from_filename(path):
    name = os.path.basename(path)

    name = re.sub(r"_scores_rank_001.*$", "", name)
    name = re.sub(r"_unrelaxed_rank_001.*$", "", name)
    name = re.sub(r"_relaxed_rank_001.*$", "", name)
    name = re.sub(r"_predicted_aligned_error.*$", "", name)
    name = re.sub(r"_pae.*$", "", name)
    name = re.sub(r"_plddt.*$", "", name)
    name = re.sub(r"_coverage.*$", "", name)
    name = re.sub(r"\.a3m$", "", name)

    return name


def find_rank001_json_files(result_dir):
    patterns = [
        os.path.join(result_dir, "**", "*scores_rank_001*.json"),
        os.path.join(result_dir, "**", "*_scores_rank_001_*.json")
    ]

    found = []
    for pattern in patterns:
        found.extend(glob.glob(pattern, recursive=True))

    return sorted(set(found))


def find_rank001_pdb_files(result_dir):
    patterns = [
        os.path.join(result_dir, "**", "*unrelaxed_rank_001*.pdb"),
        os.path.join(result_dir, "**", "*_unrelaxed_rank_001_*.pdb"),
        os.path.join(result_dir, "**", "*relaxed_rank_001*.pdb"),
        os.path.join(result_dir, "**", "*_relaxed_rank_001_*.pdb")
    ]

    found = []
    for pattern in patterns:
        found.extend(glob.glob(pattern, recursive=True))

    return sorted(set(found))


def find_a3m_files(result_dir):
    return sorted(set(glob.glob(os.path.join(result_dir, "**", "*.a3m"), recursive=True)))


def read_scores_json(path):
    with open(path, "r", encoding="utf-8") as handle:
        data = json.load(handle)

    plddt = data.get("plddt", None)
    ptm = data.get("ptm", np.nan)

    if plddt is None:
        raise ValueError(f"No plddt found in {path}")

    plddt = np.array(plddt, dtype=float)
    chromophore_indices = [pos - 1 for pos in CHROMOPHORE_POSITIONS]

    return {
        "Mean_pLDDT": float(np.mean(plddt)),
        "pTM": float(ptm) if ptm is not None else np.nan,
        "Chromophore_pLDDT_Mean_65_67": float(np.mean(plddt[chromophore_indices])),
        "Chromophore_pLDDT_Min_65_67": float(np.min(plddt[chromophore_indices])),
        "Core_pLDDT_Mean_1_220": float(np.mean(plddt[CORE_START - 1:CORE_END])),
        "CTerm_pLDDT_Mean_221_End": float(np.mean(plddt[220:])),
        "plddt_array": plddt
    }


def parse_mutation_positions(mutation_string):
    tokens = re.findall(r"[A-Z](\d+)[A-Z]", str(mutation_string))
    return [int(x) for x in tokens]


def read_ca_coordinates_from_pdb(path, start=1, end=220):
    coords = []
    residues = []

    with open(path, "r", encoding="utf-8", errors="ignore") as handle:
        for line in handle:
            if not line.startswith("ATOM"):
                continue

            atom_name = line[12:16].strip()
            if atom_name != "CA":
                continue

            try:
                resseq = int(line[22:26].strip())
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
            except ValueError:
                continue

            if start <= resseq <= end:
                residues.append(resseq)
                coords.append([x, y, z])

    return np.array(coords, dtype=float), residues


def kabsch_rmsd(P, Q):
    if P.shape != Q.shape:
        raise ValueError(f"Shape mismatch: {P.shape} vs {Q.shape}")

    P_cent = P - P.mean(axis=0)
    Q_cent = Q - Q.mean(axis=0)

    C = np.dot(P_cent.T, Q_cent)
    V, S, Wt = np.linalg.svd(C)

    d = np.sign(np.linalg.det(np.dot(V, Wt)))
    D = np.diag([1.0, 1.0, d])

    U = np.dot(np.dot(V, D), Wt)

    P_rot = np.dot(P_cent, U)
    diff = P_rot - Q_cent

    return float(np.sqrt(np.mean(np.sum(diff * diff, axis=1))))


def read_sequence_from_a3m(path):
    sequence_chunks = []
    reading_first_sequence = False
    first_header_seen = False

    with open(path, "r", encoding="utf-8", errors="ignore") as handle:
        for raw_line in handle:
            line = raw_line.strip()

            if line == "":
                continue

            if line.startswith(">"):
                if not first_header_seen:
                    first_header_seen = True
                    reading_first_sequence = True
                    continue
                else:
                    break

            if reading_first_sequence:
                sequence_chunks.append(line)

    sequence = "".join(sequence_chunks)
    sequence = re.sub(r"[a-z]", "", sequence)
    sequence = sequence.replace("-", "")
    sequence = normalize_sequence(sequence)

    if len(sequence) == 0:
        return None

    return sequence


THREE_TO_ONE = {
    "ALA": "A", "ARG": "R", "ASN": "N", "ASP": "D", "CYS": "C",
    "GLN": "Q", "GLU": "E", "GLY": "G", "HIS": "H", "ILE": "I",
    "LEU": "L", "LYS": "K", "MET": "M", "PHE": "F", "PRO": "P",
    "SER": "S", "THR": "T", "TRP": "W", "TYR": "Y", "VAL": "V"
}


def read_sequence_from_pdb(path):
    residues = []
    seen = set()

    with open(path, "r", encoding="utf-8", errors="ignore") as handle:
        for line in handle:
            if not line.startswith("ATOM"):
                continue

            atom_name = line[12:16].strip()
            if atom_name != "CA":
                continue

            resname = line[17:20].strip()
            chain_id = line[21].strip()
            resseq = line[22:26].strip()
            key = (chain_id, resseq)

            if key in seen:
                continue

            seen.add(key)
            residues.append(THREE_TO_ONE.get(resname, "X"))

    sequence = "".join(residues)

    if "X" in sequence:
        return None

    return sequence


def find_matching_key(query_id, key_collection):
    exact = [key for key in key_collection if key == query_id]
    if exact:
        return exact[0]

    contains = [key for key in key_collection if query_id in key]
    if contains:
        return contains[0]

    return None


def save_barplot(df, x_col, y_col, title, ylabel, output_path, rotate=30):
    plt.figure(figsize=(9, 5))
    plt.bar(df[x_col].astype(str), df[y_col])
    plt.title(title)
    plt.xlabel(x_col)
    plt.ylabel(ylabel)
    plt.xticks(rotation=rotate, ha="right")
    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    plt.show()
    plt.close()


def save_scatter_top24(df_all, df_final, x_col, y_col, title, xlabel, ylabel, output_path):
    plt.figure(figsize=(8, 6))
    plt.scatter(df_all[x_col], df_all[y_col], label="Top24 candidates")
    plt.scatter(df_final[x_col], df_final[y_col], label="Final selected 6", marker="x")

    for _, row in df_final.iterrows():
        plt.text(
            row[x_col],
            row[y_col],
            f"Seq {row['Seq_ID']}",
            fontsize=9,
            ha="left",
            va="bottom"
        )

    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.legend()
    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    plt.show()
    plt.close()


# ============================================================
# 4. Extract ColabFold archive
# ============================================================

print("\nExtracting ColabFold results archive...")

if os.path.exists(EXTRACT_DIR):
    shutil.rmtree(EXTRACT_DIR)

os.makedirs(EXTRACT_DIR, exist_ok=True)

recursively_extract_zip(COLABFOLD_RESULTS_ZIP, EXTRACT_DIR)

json_files = find_rank001_json_files(EXTRACT_DIR)
pdb_files = find_rank001_pdb_files(EXTRACT_DIR)
a3m_files = find_a3m_files(EXTRACT_DIR)

print(f"Rank 001 JSON files found: {len(json_files)}")
print(f"Rank 001 PDB files found: {len(pdb_files)}")
print(f"A3M files found: {len(a3m_files)}")

if len(json_files) == 0 or len(pdb_files) == 0:
    raise FileNotFoundError(
        "Не найдены rank_001 JSON/PDB файлы. "
        "Проверьте, что загружен именно архив результатов ColabFold, а не FASTA-архив."
    )


# ============================================================
# 5. Build maps
# ============================================================

json_by_key = {extract_query_id_from_filename(path): path for path in json_files}
pdb_by_key = {extract_query_id_from_filename(path): path for path in pdb_files}
a3m_by_key = {extract_query_id_from_filename(path): path for path in a3m_files}

print("\nDetected result keys:")
for key in sorted(json_by_key.keys())[:10]:
    print(key)

wt_keys = [key for key in pdb_by_key if "sfGFP_WT" in key]

if len(wt_keys) == 0:
    raise ValueError("sfGFP_WT rank_001 PDB not found in archive.")

wt_key = wt_keys[0]
wt_pdb = pdb_by_key[wt_key]
wt_coords, wt_residues = read_ca_coordinates_from_pdb(wt_pdb, CORE_START, CORE_END)

if len(wt_coords) == 0:
    raise ValueError("Could not read CA coordinates from WT PDB.")

print(f"\nWT key: {wt_key}")
print(f"WT core CA atoms: {len(wt_coords)}")


# ============================================================
# 6. Optional top24 metadata
# ============================================================

top24_df = None

if top24_csv_path is not None:
    top24_df = pd.read_csv(top24_csv_path)
    print("\nLoaded top24 metadata:")
    print(top24_df.shape)
    display(top24_df.head())

top24_by_query = {}

if top24_df is not None and "ColabFold_Query_ID" in top24_df.columns:
    for _, row in top24_df.iterrows():
        top24_by_query[str(row["ColabFold_Query_ID"])] = row.to_dict()


# ============================================================
# 7. Collect Stage 4 metrics
# ============================================================

stage4_records = []

all_query_ids = sorted(
    [
        key for key in json_by_key.keys()
        if key != wt_key and "sfGFP_WT" not in key
    ]
)

for query_id in all_query_ids:
    json_key = find_matching_key(query_id, json_by_key.keys())
    pdb_key = find_matching_key(query_id, pdb_by_key.keys())

    if json_key is None or pdb_key is None:
        continue

    json_path = json_by_key[json_key]
    pdb_path = pdb_by_key[pdb_key]

    score_data = read_scores_json(json_path)
    plddt = score_data["plddt_array"]

    metadata = top24_by_query.get(query_id, {})

    mutations = metadata.get("Mutations", "")
    mutation_positions = parse_mutation_positions(mutations)

    if len(mutation_positions) > 0:
        valid_indices = [pos - 1 for pos in mutation_positions if 1 <= pos <= len(plddt)]
        mutation_site_plddt_min = float(np.min(plddt[valid_indices]))
        mutation_site_plddt_mean = float(np.mean(plddt[valid_indices]))
    else:
        mutation_site_plddt_min = np.nan
        mutation_site_plddt_mean = np.nan

    coords, residues = read_ca_coordinates_from_pdb(pdb_path, CORE_START, CORE_END)

    if coords.shape == wt_coords.shape:
        core_rmsd = kabsch_rmsd(coords, wt_coords)
    else:
        core_rmsd = np.nan

    sequence = metadata.get("Sequence", None)

    if sequence is None or pd.isna(sequence) or str(sequence).strip() == "":
        a3m_key = find_matching_key(query_id, a3m_by_key.keys())

        if a3m_key is not None:
            sequence = read_sequence_from_a3m(a3m_by_key[a3m_key])

    if sequence is None or pd.isna(sequence) or str(sequence).strip() == "":
        sequence = read_sequence_from_pdb(pdb_path)

    record = {
        "ColabFold_Query_ID": query_id,
        "Candidate_ID": metadata.get("Candidate_ID", query_id.replace("Query_", "CAND_")),
        "Design_Family": metadata.get("Design_Family", ""),
        "Mutations": mutations,
        "Sequence": normalize_sequence(sequence) if sequence is not None else "",
        "Length": len(normalize_sequence(sequence)) if sequence is not None else np.nan,
        "Mutation_Count": len(parse_mutation_positions(mutations)) if mutations != "" else np.nan,
        "Approx_Net_Charge": metadata.get("Approx_Net_Charge", np.nan),
        "Charge_Delta_More_Negative_vs_sfGFP": metadata.get("Charge_Delta_More_Negative_vs_sfGFP", np.nan),
        "Local_Brightness_Evidence_Score": metadata.get("Local_Brightness_Evidence_Score", np.nan),
        "Stability_Proxy_Score": metadata.get("Stability_Proxy_Score", np.nan),
        "Risk_Penalty": metadata.get("Risk_Penalty", np.nan),
        "Pre_ColabFold_MultiObjective_Score": metadata.get("Pre_ColabFold_MultiObjective_Score", np.nan),
        "Mean_pLDDT": score_data["Mean_pLDDT"],
        "pTM": score_data["pTM"],
        "Chromophore_pLDDT_Mean_65_67": score_data["Chromophore_pLDDT_Mean_65_67"],
        "Chromophore_pLDDT_Min_65_67": score_data["Chromophore_pLDDT_Min_65_67"],
        "Core_pLDDT_Mean_1_220": score_data["Core_pLDDT_Mean_1_220"],
        "CTerm_pLDDT_Mean_221_End": score_data["CTerm_pLDDT_Mean_221_End"],
        "Mutation_Site_pLDDT_Mean": mutation_site_plddt_mean,
        "Mutation_Site_pLDDT_Min": mutation_site_plddt_min,
        "Core_RMSD_to_WT_A": core_rmsd,
        "ColabFold_JSON": json_path,
        "ColabFold_PDB": pdb_path
    }

    stage4_records.append(record)

stage4_df = pd.DataFrame(stage4_records)

if stage4_df.empty:
    raise ValueError("No candidate metrics were collected from archive.")

stage4_df["Structural_Pass"] = (
    (stage4_df["Mean_pLDDT"] >= 90) &
    (stage4_df["Chromophore_pLDDT_Min_65_67"] >= 85) &
    (stage4_df["Core_RMSD_to_WT_A"] <= 1.0)
)

stage4_df["Pre_ColabFold_MultiObjective_Score"] = pd.to_numeric(
    stage4_df["Pre_ColabFold_MultiObjective_Score"],
    errors="coerce"
)

if stage4_df["Pre_ColabFold_MultiObjective_Score"].notna().any():
    pre_score = stage4_df["Pre_ColabFold_MultiObjective_Score"].fillna(
        stage4_df["Pre_ColabFold_MultiObjective_Score"].median()
    )
else:
    pre_score = pd.Series(np.ones(stage4_df.shape[0]) * 0.5)

mean_plddt = pd.to_numeric(stage4_df["Mean_pLDDT"], errors="coerce")
rmsd = pd.to_numeric(stage4_df["Core_RMSD_to_WT_A"], errors="coerce")


def minmax(series):
    series = pd.to_numeric(series, errors="coerce")
    low = series.min()
    high = series.max()

    if pd.isna(low) or pd.isna(high) or high == low:
        return pd.Series(np.ones(len(series)) * 0.5, index=series.index)

    return (series - low) / (high - low)


stage4_df["PreScore_Norm"] = minmax(pre_score)
stage4_df["pLDDT_Norm"] = minmax(mean_plddt)
stage4_df["RMSD_Norm"] = 1 - minmax(rmsd)

stage4_df["Final_Computational_Score"] = (
    0.55 * stage4_df["PreScore_Norm"] +
    0.30 * stage4_df["pLDDT_Norm"] +
    0.15 * stage4_df["RMSD_Norm"]
)

stage4_df.loc[~stage4_df["Structural_Pass"], "Final_Computational_Score"] -= 1.0

stage4_metrics_path = os.path.join(OUTPUT_DIR, "stage4_colabfold_metrics_from_uploaded_archive.csv")
stage4_df.to_csv(stage4_metrics_path, index=False)

print("\nStage 4 metrics collected from archive:")
display(
    stage4_df[
        [
            "ColabFold_Query_ID",
            "Mutations",
            "Sequence",
            "Mean_pLDDT",
            "pTM",
            "Chromophore_pLDDT_Min_65_67",
            "Core_RMSD_to_WT_A",
            "Structural_Pass",
            "Final_Computational_Score"
        ]
    ].head(30)
)

print(f"\nSaved: {stage4_metrics_path}")


# ============================================================
# 8. Extract final 6
# ============================================================

final_rows = []

for item in FINAL_QUERY_ORDER:
    seq_id = item["Seq_ID"]
    query_id = item["ColabFold_Query_ID"]

    match = stage4_df[stage4_df["ColabFold_Query_ID"].str.contains(query_id, regex=False, na=False)].copy()

    if match.shape[0] != 1:
        raise ValueError(
            f"Expected exactly one row for {query_id}, found {match.shape[0]}. "
            "Check that the archive contains this query."
        )

    row = match.iloc[0].to_dict()

    row["Seq_ID"] = seq_id
    row["Team_Name"] = TEAM_NAME
    row["Recommended_Role"] = item["Recommended_Role"]

    if row.get("Mutations", "") == "":
        row["Mutations"] = item["Mutations"]

    if row.get("Design_Family", "") == "":
        row["Design_Family"] = item["Design_Family"]

    row["Sequence"] = validate_submission_sequence(seq_id, row["Sequence"])

    if bool(row["Structural_Pass"]) is not True:
        raise ValueError(f"{query_id} has Structural_Pass != True")

    final_rows.append(row)

final6_df = pd.DataFrame(final_rows)
final6_df = final6_df.sort_values("Seq_ID").reset_index(drop=True)

print("\nFinal selected 6:")
display(
    final6_df[
        [
            "Seq_ID",
            "Recommended_Role",
            "ColabFold_Query_ID",
            "Design_Family",
            "Mutations",
            "Length",
            "Mean_pLDDT",
            "pTM",
            "Chromophore_pLDDT_Min_65_67",
            "Core_RMSD_to_WT_A",
            "Structural_Pass",
            "Final_Computational_Score"
        ]
    ]
)


# ============================================================
# 9. Create submission CSV
# ============================================================

submission_df = final6_df[["Team_Name", "Seq_ID", "Sequence"]].copy()

submission_df["Team_Name"] = TEAM_NAME
submission_df["Seq_ID"] = submission_df["Seq_ID"].astype(int)
submission_df["Sequence"] = submission_df["Sequence"].map(normalize_sequence)

if list(submission_df.columns) != ["Team_Name", "Seq_ID", "Sequence"]:
    raise ValueError("Submission columns are incorrect.")

if submission_df.shape[0] != 6:
    raise ValueError(f"Submission has {submission_df.shape[0]} rows, expected 6.")

if submission_df["Sequence"].duplicated().any():
    raise ValueError("Submission contains duplicated sequences.")

for _, row in submission_df.iterrows():
    validate_submission_sequence(row["Seq_ID"], row["Sequence"])

submission_path = os.path.join(OUTPUT_DIR, "submission_GeneMeow.csv")
submission_df.to_csv(submission_path, index=False)

print("\nFinal submission table:")
display(submission_df)

print(f"Saved: {submission_path}")


# ============================================================
# 10. Save summary
# ============================================================

summary_columns = [
    "Seq_ID",
    "Recommended_Role",
    "ColabFold_Query_ID",
    "Design_Family",
    "Mutations",
    "Length",
    "Mutation_Count",
    "Approx_Net_Charge",
    "Charge_Delta_More_Negative_vs_sfGFP",
    "Local_Brightness_Evidence_Score",
    "Stability_Proxy_Score",
    "Risk_Penalty",
    "Pre_ColabFold_MultiObjective_Score",
    "Mean_pLDDT",
    "pTM",
    "Chromophore_pLDDT_Min_65_67",
    "Mutation_Site_pLDDT_Min",
    "Core_RMSD_to_WT_A",
    "Structural_Pass",
    "Final_Computational_Score"
]

summary_columns_existing = [col for col in summary_columns if col in final6_df.columns]

final6_summary = final6_df[summary_columns_existing].copy()

summary_path = os.path.join(OUTPUT_DIR, "final6_GeneMeow_summary.csv")
final6_summary.to_csv(summary_path, index=False)

print(f"Saved: {summary_path}")


# ============================================================
# 11. Generate figures
# ============================================================

fig_final_score = os.path.join(FIGURES_DIR, "final6_final_computational_score.png")
fig_plddt = os.path.join(FIGURES_DIR, "final6_mean_plddt.png")
fig_chromophore = os.path.join(FIGURES_DIR, "final6_chromophore_plddt_min.png")
fig_rmsd = os.path.join(FIGURES_DIR, "final6_core_rmsd_to_wt.png")
fig_scatter = os.path.join(FIGURES_DIR, "top24_charge_vs_final_score_highlight_final6.png")

plot_df = final6_summary.copy()
plot_df["Seq_Label"] = plot_df["Seq_ID"].apply(lambda x: f"Seq {x}")

save_barplot(
    plot_df,
    "Seq_Label",
    "Final_Computational_Score",
    "Final computational score for selected GeneMeow candidates",
    "Final computational score",
    fig_final_score
)

save_barplot(
    plot_df,
    "Seq_Label",
    "Mean_pLDDT",
    "ColabFold mean pLDDT for selected GeneMeow candidates",
    "Mean pLDDT",
    fig_plddt
)

save_barplot(
    plot_df,
    "Seq_Label",
    "Chromophore_pLDDT_Min_65_67",
    "Minimum pLDDT in chromophore-forming positions 65-67",
    "Minimum pLDDT, positions 65-67",
    fig_chromophore
)

save_barplot(
    plot_df,
    "Seq_Label",
    "Core_RMSD_to_WT_A",
    "Core RMSD to WT sfGFP for selected GeneMeow candidates",
    "Core RMSD to WT, Å",
    fig_rmsd
)

if "Charge_Delta_More_Negative_vs_sfGFP" in stage4_df.columns:
    scatter_all = stage4_df.copy()
    scatter_all["Charge_Delta_More_Negative_vs_sfGFP"] = pd.to_numeric(
        scatter_all["Charge_Delta_More_Negative_vs_sfGFP"],
        errors="coerce"
    )

    scatter_final = final6_df.copy()
    scatter_final["Charge_Delta_More_Negative_vs_sfGFP"] = pd.to_numeric(
        scatter_final["Charge_Delta_More_Negative_vs_sfGFP"],
        errors="coerce"
    )

    if scatter_all["Charge_Delta_More_Negative_vs_sfGFP"].notna().any():
        save_scatter_top24(
            scatter_all,
            scatter_final,
            "Charge_Delta_More_Negative_vs_sfGFP",
            "Final_Computational_Score",
            "Top24 charge shift versus final computational score",
            "Charge shift toward negative vs sfGFP",
            "Final computational score",
            fig_scatter
        )

print("\nSaved figures:")
for path in [fig_final_score, fig_plddt, fig_chromophore, fig_rmsd]:
    print(path)

if os.path.exists(fig_scatter):
    print(fig_scatter)


# ============================================================
# 12. Copy raw ColabFold PNGs only for final 6
# ============================================================

found_raw_plots = []

for query_id in final6_df["ColabFold_Query_ID"]:
    patterns = [
        os.path.join(EXTRACT_DIR, "**", f"{query_id}*plddt*.png"),
        os.path.join(EXTRACT_DIR, "**", f"{query_id}*pae*.png"),
        os.path.join(EXTRACT_DIR, "**", f"{query_id}*coverage*.png")
    ]

    for pattern in patterns:
        for src in glob.glob(pattern, recursive=True):
            dst_name = f"{query_id}_{os.path.basename(src)}"
            dst = os.path.join(RAW_COLABFOLD_FIGURES_DIR, dst_name)
            shutil.copy2(src, dst)
            found_raw_plots.append(dst)

print(f"\nRaw ColabFold plots copied: {len(found_raw_plots)}")


# ============================================================
# 13. Memory-safe packaging
# ============================================================

figures_zip_base = "/content/GeneMeow_figures_for_PDF"
figures_zip_path = shutil.make_archive(
    figures_zip_base,
    "zip",
    FIGURES_DIR
)

print(f"\nFigures zip saved: {figures_zip_path}")

if os.path.exists(MINIMAL_PACKAGE_DIR):
    shutil.rmtree(MINIMAL_PACKAGE_DIR)

os.makedirs(MINIMAL_PACKAGE_DIR, exist_ok=True)

essential_files = [
    submission_path,
    summary_path,
    stage4_metrics_path,
    figures_zip_path
]

for src in essential_files:
    if os.path.exists(src):
        dst = os.path.join(MINIMAL_PACKAGE_DIR, os.path.basename(src))
        shutil.copy2(src, dst)
        print(f"Copied to minimal package: {dst}")
    else:
        print(f"WARNING: missing file: {src}")

minimal_zip_base = "/content/GeneMeow_minimal_submission_package"
minimal_zip_path = shutil.make_archive(
    minimal_zip_base,
    "zip",
    MINIMAL_PACKAGE_DIR
)

print(f"\nMinimal package zip saved: {minimal_zip_path}")


# ============================================================
# 14. Download only essential outputs
# ============================================================

files.download(submission_path)
files.download(summary_path)
files.download(stage4_metrics_path)
files.download(figures_zip_path)
files.download(minimal_zip_path)

print("\nDONE.")
print("Main file for competition upload:")
print(submission_path)