# -*- coding: utf-8 -*-
"""GFP_2026_design_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kfdqSSvPi_HX9QtLbQKsjdgv04ssgbxE
"""

import os
import re
import pandas as pd
import numpy as np

BASE_DIR = "/content"

AA_REFERENCE_FILE = os.path.join(BASE_DIR, "AAseqs of 5 GFP proteins_20260511.txt")
GFP_DATA_FILE = os.path.join(BASE_DIR, "GFP_data.xlsx")
EXCLUSION_FILE = os.path.join(BASE_DIR, "Exclusion_List.csv")
SUBMISSION_TEMPLATE_FILE = os.path.join(BASE_DIR, "submission_template.csv")

required_files = [
    AA_REFERENCE_FILE,
    GFP_DATA_FILE,
    EXCLUSION_FILE,
    SUBMISSION_TEMPLATE_FILE
]

print("Checking required files...\n")

for path in required_files:
    if os.path.exists(path):
        size_mb = os.path.getsize(path) / 1024 / 1024
        print(f"OK: {os.path.basename(path)} | {size_mb:.2f} MB")
    else:
        print(f"MISSING: {os.path.basename(path)}")

ALLOWED_AA = set("ACDEFGHIKLMNPQRSTVWY")

def normalize_sequence(seq):
    if pd.isna(seq):
        return ""
    seq = str(seq)
    seq = re.sub(r"\s+", "", seq)
    seq = seq.upper()
    return seq


def parse_reference_file(path):
    refs = {}
    current_name = None
    current_seq = []

    with open(path, "r", encoding="utf-8-sig") as handle:
        for raw_line in handle:
            line = raw_line.strip()

            if line == "":
                continue

            if line.startswith("#"):
                continue

            if line.startswith(">"):
                if current_name is not None:
                    refs[current_name] = normalize_sequence("".join(current_seq))

                current_name = line[1:].strip()
                current_seq = []
            else:
                if current_name is not None:
                    current_seq.append(line)

        if current_name is not None:
            refs[current_name] = normalize_sequence("".join(current_seq))

    return refs


def validate_protein_sequence(name, seq):
    seq = normalize_sequence(seq)

    errors = []

    if not seq.startswith("M"):
        errors.append("does not start with M")

    if len(seq) < 220 or len(seq) > 250:
        errors.append(f"length is {len(seq)}, expected 220–250")

    invalid = sorted(set(seq) - ALLOWED_AA)
    if invalid:
        errors.append(f"invalid characters: {''.join(invalid)}")

    if errors:
        raise ValueError(f"{name}: " + "; ".join(errors))

    return seq


refs = parse_reference_file(AA_REFERENCE_FILE)

print("Reference GFPs found:")
for name, seq in refs.items():
    print(f"{name}: length = {len(seq)}, starts with = {seq[:10]}, chromophore 65-67 = {seq[64:67]}")

if "sfGFP" not in refs:
    raise ValueError("sfGFP not found in reference file.")

if "avGFP" not in refs:
    raise ValueError("avGFP not found in reference file.")

sfGFP = validate_protein_sequence("sfGFP", refs["sfGFP"])
avGFP = validate_protein_sequence("avGFP", refs["avGFP"])

print("\nMain references loaded successfully.")
print(f"sfGFP length: {len(sfGFP)}")
print(f"avGFP length: {len(avGFP)}")
print(f"sfGFP chromophore 65-67: {sfGFP[64:67]}")
print(f"avGFP chromophore 65-67: {avGFP[64:67]}")

def load_exclusion_sequences(path):
    df = pd.read_csv(path, dtype=str, keep_default_na=False)
    excluded = set()

    sequence_columns = [
        c for c in df.columns
        if str(c).strip().lower() in {
            "sequence",
            "seq",
            "aa_sequence",
            "protein_sequence",
            "amino_acid_sequence"
        }
    ]

    columns_to_scan = sequence_columns if sequence_columns else list(df.columns)

    for col in columns_to_scan:
        for value in df[col].astype(str):
            candidate = normalize_sequence(value)

            if len(candidate) >= 50 and set(candidate) <= ALLOWED_AA:
                excluded.add(candidate)

    return excluded, df


excluded_sequences, exclusion_df = load_exclusion_sequences(EXCLUSION_FILE)

print("Exclusion_List.csv loaded.")
print(f"Rows: {exclusion_df.shape[0]}")
print(f"Columns: {list(exclusion_df.columns)}")
print(f"Recognized protein-like excluded sequences: {len(excluded_sequences)}")

print("\nReference checks:")
print(f"sfGFP in exclusion list: {sfGFP in excluded_sequences}")
print(f"avGFP in exclusion list: {avGFP in excluded_sequences}")

excel = pd.ExcelFile(GFP_DATA_FILE)

print("Sheets in GFP_data.xlsx:")
print(excel.sheet_names)

brightness_df = pd.read_excel(GFP_DATA_FILE, sheet_name="brightness", dtype=str)
beforetop_df = pd.read_excel(GFP_DATA_FILE, sheet_name="beforetopseqs", dtype=str)

print("\nbrightness sheet:")
print(brightness_df.shape)
print(brightness_df.head())

print("\nbeforetopseqs sheet:")
print(beforetop_df.shape)
print(beforetop_df.head())

required_brightness_cols = {"aaMutations", "GFP type", "Brightness"}
missing = required_brightness_cols - set(brightness_df.columns)

if missing:
    raise ValueError(f"Missing columns in brightness sheet: {missing}")

print("\nCounts by GFP type:")
display(
    brightness_df.groupby("GFP type", dropna=False)
    .size()
    .reset_index(name="n_rows")
    .sort_values("n_rows", ascending=False)
)

template_df = pd.read_csv(SUBMISSION_TEMPLATE_FILE, dtype=str, keep_default_na=False)

print("submission_template.csv columns:")
print(list(template_df.columns))

expected_cols = ["Team_Name", "Seq_ID", "Sequence"]

if list(template_df.columns) != expected_cols:
    raise ValueError(
        f"Wrong template columns. Expected {expected_cols}, got {list(template_df.columns)}"
    )

print("\nTemplate format is correct.")
display(template_df.head())

!pip -q install scikit-learn

import re
import json
import numpy as np
import pandas as pd

from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import Ridge
from sklearn.isotonic import IsotonicRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error


def parse_mutation_string(value):
    if pd.isna(value):
        return []

    value = str(value).strip()

    if value == "":
        return []

    if value.upper() in {"WT", "WILDTYPE", "WILD_TYPE", "NONE", "NAN"}:
        return []

    tokens = re.findall(r"[A-Z]\d+[A-Z]", value)
    return tokens


def mutation_list_to_feature_dict(mutations):
    return {mutation: 1.0 for mutation in mutations}


def mutations_relative_to_reference(reference_seq, query_seq):
    reference_seq = normalize_sequence(reference_seq)
    query_seq = normalize_sequence(query_seq)

    if len(reference_seq) != len(query_seq):
        raise ValueError(
            f"Reference and query lengths differ: {len(reference_seq)} vs {len(query_seq)}"
        )

    mutations = []

    for pos, (ref_aa, query_aa) in enumerate(zip(reference_seq, query_seq), start=1):
        if ref_aa != query_aa:
            mutations.append(f"{ref_aa}{pos}{query_aa}")

    return mutations


brightness_df["Brightness"] = pd.to_numeric(brightness_df["Brightness"], errors="coerce")
brightness_df["GFP type"] = brightness_df["GFP type"].astype(str)

av_data = brightness_df[
    (brightness_df["GFP type"].str.strip() == "avGFP") &
    (brightness_df["Brightness"].notna())
].copy()

av_data["mutation_tokens"] = av_data["aaMutations"].apply(parse_mutation_string)
av_data["feature_dict"] = av_data["mutation_tokens"].apply(mutation_list_to_feature_dict)
av_data["mutation_count"] = av_data["mutation_tokens"].apply(len)

print("avGFP data prepared:")
print(f"Rows: {av_data.shape[0]}")
print(f"Brightness min: {av_data['Brightness'].min():.4f}")
print(f"Brightness max: {av_data['Brightness'].max():.4f}")
print(f"Brightness mean: {av_data['Brightness'].mean():.4f}")

print("\nMutation count distribution:")
display(
    av_data.groupby("mutation_count")
    .size()
    .reset_index(name="n_rows")
    .sort_values("mutation_count")
)


train_df, temp_df = train_test_split(
    av_data,
    test_size=0.30,
    random_state=42
)

cal_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=42
)

print("\nSplit sizes:")
print(f"Train: {train_df.shape[0]}")
print(f"Calibration: {cal_df.shape[0]}")
print(f"Test: {test_df.shape[0]}")


vectorizer = DictVectorizer(sparse=True)

X_train = vectorizer.fit_transform(train_df["feature_dict"])
X_cal = vectorizer.transform(cal_df["feature_dict"])
X_test = vectorizer.transform(test_df["feature_dict"])

y_train = train_df["Brightness"].values.astype(float)
y_cal = cal_df["Brightness"].values.astype(float)
y_test = test_df["Brightness"].values.astype(float)

print("\nFeature matrix:")
print(f"Number of mutation features: {len(vectorizer.feature_names_)}")


ridge_model = Ridge(alpha=1.0)
ridge_model.fit(X_train, y_train)

cal_raw = ridge_model.predict(X_cal)
test_raw = ridge_model.predict(X_test)

ridge_r2 = r2_score(y_test, test_raw)
ridge_mae = mean_absolute_error(y_test, test_raw)

print("\nRaw Ridge model:")
print(f"Test R2: {ridge_r2:.4f}")
print(f"Test MAE: {ridge_mae:.4f}")


isotonic_model = IsotonicRegression(out_of_bounds="clip")
isotonic_model.fit(cal_raw, y_cal)

test_pred = isotonic_model.predict(test_raw)

calibrated_r2 = r2_score(y_test, test_pred)
calibrated_mae = mean_absolute_error(y_test, test_pred)

print("\nRidge + isotonic calibration:")
print(f"Test R2: {calibrated_r2:.4f}")
print(f"Test MAE: {calibrated_mae:.4f}")


def predict_brightness_from_sequence(seq, reference_seq=avGFP):
    seq = normalize_sequence(seq)
    reference_seq = normalize_sequence(reference_seq)

    if len(seq) != len(reference_seq):
        raise ValueError(
            f"Sequence length differs from reference: {len(seq)} vs {len(reference_seq)}"
        )

    mutations = mutations_relative_to_reference(reference_seq, seq)
    feature_dict = mutation_list_to_feature_dict(mutations)

    X = vectorizer.transform([feature_dict])
    raw_pred = ridge_model.predict(X)
    calibrated_pred = isotonic_model.predict(raw_pred)

    return float(calibrated_pred[0])


pred_avGFP_WT = predict_brightness_from_sequence(avGFP, avGFP)
pred_sfGFP = predict_brightness_from_sequence(sfGFP, avGFP)

print("\nReference brightness predictions:")
print(f"Predicted avGFP WT brightness: {pred_avGFP_WT:.4f}")
print(f"Predicted sfGFP brightness in avGFP-transfer model: {pred_sfGFP:.4f}")


brightness_model_metrics = {
    "n_avGFP_rows": int(av_data.shape[0]),
    "n_train": int(train_df.shape[0]),
    "n_calibration": int(cal_df.shape[0]),
    "n_test": int(test_df.shape[0]),
    "n_mutation_features": int(len(vectorizer.feature_names_)),
    "ridge_test_r2": float(ridge_r2),
    "ridge_test_mae": float(ridge_mae),
    "calibrated_test_r2": float(calibrated_r2),
    "calibrated_test_mae": float(calibrated_mae),
    "predicted_avGFP_WT_brightness": float(pred_avGFP_WT),
    "predicted_sfGFP_brightness_transfer_model": float(pred_sfGFP)
}

print("\nBrightness model metrics:")
print(json.dumps(brightness_model_metrics, indent=2))

single_mut_df = av_data[av_data["mutation_count"] == 1].copy()

single_mut_df["single_mutation"] = single_mut_df["mutation_tokens"].apply(
    lambda x: x[0] if len(x) == 1 else None
)

single_mut_df = single_mut_df.dropna(subset=["single_mutation"]).copy()
feature_names = np.array(vectorizer.feature_names_)
coef_values = ridge_model.coef_

coef_df = pd.DataFrame({
    "mutation": feature_names,
    "ridge_coefficient": coef_values
})

single_mut_summary = (
    single_mut_df
    .groupby("single_mutation", as_index=False)
    .agg(
        observed_single_brightness_mean=("Brightness", "mean"),
        observed_single_brightness_max=("Brightness", "max"),
        observed_single_brightness_min=("Brightness", "min"),
        n_observations=("Brightness", "size")
    )
    .rename(columns={"single_mutation": "mutation"})
)

single_mut_summary = single_mut_summary.merge(
    coef_df,
    on="mutation",
    how="left"
)

single_mut_summary["delta_vs_avGFP_WT_pred"] = (
    single_mut_summary["observed_single_brightness_mean"] - pred_avGFP_WT
)

single_mut_summary = single_mut_summary.sort_values(
    ["observed_single_brightness_mean", "ridge_coefficient"],
    ascending=False
).reset_index(drop=True)

print("Top 30 observed single mutations by mean brightness:")
display(single_mut_summary.head(30))

print("\nBottom 30 observed single mutations by mean brightness:")
display(single_mut_summary.tail(30))

single_mut_summary_path = "/content/single_mutation_brightness_summary.csv"
single_mut_summary.to_csv(single_mut_summary_path, index=False)

print(f"\nSaved: {single_mut_summary_path}")

mutations_to_check = [
    "Q68L",
    "H147S",
    "F45L",
    "N148K",
    "N163Y",
    "S207L",

    # friend-like / DMS-supercharge mutations
    "D19E",
    "L44M",
    "R73L",
    "N198D",
    "H231Y",
    "K101E",
    "K156E",
    "K166E",
    "K214E",
    "N212D"
]

check_rows = []

for mutation in mutations_to_check:
    single_row = single_mut_summary[single_mut_summary["mutation"] == mutation]
    coef_row = coef_df[coef_df["mutation"] == mutation]

    if len(single_row) > 0:
        observed_mean = float(single_row["observed_single_brightness_mean"].iloc[0])
        observed_max = float(single_row["observed_single_brightness_max"].iloc[0])
        observed_min = float(single_row["observed_single_brightness_min"].iloc[0])
        n_obs = int(single_row["n_observations"].iloc[0])
    else:
        observed_mean = np.nan
        observed_max = np.nan
        observed_min = np.nan
        n_obs = 0

    if len(coef_row) > 0:
        coef = float(coef_row["ridge_coefficient"].iloc[0])
    else:
        coef = np.nan

    check_rows.append({
        "mutation": mutation,
        "observed_single_brightness_mean": observed_mean,
        "observed_single_brightness_min": observed_min,
        "observed_single_brightness_max": observed_max,
        "n_single_observations": n_obs,
        "ridge_coefficient": coef
    })

mutation_check_df = pd.DataFrame(check_rows)

print("Selected mutation diagnostics:")
display(mutation_check_df)

mutation_check_path = "/content/selected_mutation_diagnostics.csv"
mutation_check_df.to_csv(mutation_check_path, index=False)

print(f"Saved: {mutation_check_path}")

import os
import re
import json
import shutil
import itertools
import numpy as np
import pandas as pd
from datetime import datetime
from google.colab import files


OUTPUT_DIR_V2 = "/content/gfp_2026_stage3_v2_outputs"
COLABFOLD_FASTA_DIR_V2 = os.path.join(OUTPUT_DIR_V2, "colabfold_top24_fasta_v2")

os.makedirs(OUTPUT_DIR_V2, exist_ok=True)
os.makedirs(COLABFOLD_FASTA_DIR_V2, exist_ok=True)


required_variables = [
    "sfGFP",
    "avGFP",
    "excluded_sequences",
    "beforetop_df",
    "single_mut_summary",
    "pred_avGFP_WT"
]

missing_variables = []

for variable_name in required_variables:
    if variable_name not in globals():
        missing_variables.append(variable_name)

if missing_variables:
    raise NameError(
        "not found "
        + ", ".join(missing_variables)
        + ". First, complete steps 1 and 2."
    )


ALLOWED_AA = set("ACDEFGHIKLMNPQRSTVWY")


def normalize_sequence(seq):
    if pd.isna(seq):
        return ""
    seq = str(seq)
    seq = re.sub(r"\s+", "", seq)
    seq = seq.upper()
    return seq


def validate_protein_sequence_local(name, seq):
    seq = normalize_sequence(seq)
    errors = []

    if not seq.startswith("M"):
        errors.append("does not start with M")

    if len(seq) < 220 or len(seq) > 250:
        errors.append(f"length is {len(seq)}, expected 220–250")

    invalid = sorted(set(seq) - ALLOWED_AA)
    if invalid:
        errors.append(f"invalid characters: {''.join(invalid)}")

    if errors:
        raise ValueError(f"{name}: " + "; ".join(errors))

    return seq


def parse_mutation_token(token):
    token = str(token).strip()
    match = re.fullmatch(r"([A-Z])(\d+)([A-Z])", token)

    if match is None:
        raise ValueError(f"Bad mutation token: {token}")

    ref_aa = match.group(1)
    pos = int(match.group(2))
    alt_aa = match.group(3)

    return ref_aa, pos, alt_aa


def apply_mutations_local(parent_seq, mutations):
    parent_seq = normalize_sequence(parent_seq)
    seq = list(parent_seq)
    used_positions = set()

    for mutation in mutations:
        ref_aa, pos, alt_aa = parse_mutation_token(mutation)

        if pos < 1 or pos > len(seq):
            raise ValueError(f"{mutation}: position outside sequence length {len(seq)}")

        if pos in used_positions:
            raise ValueError(f"{mutation}: position {pos} is mutated twice")

        observed = seq[pos - 1]

        if observed != ref_aa:
            raise ValueError(
                f"{mutation}: expected {ref_aa} at position {pos}, observed {observed}"
            )

        seq[pos - 1] = alt_aa
        used_positions.add(pos)

    return "".join(seq)


def chromophore_preserved(parent_seq, query_seq):
    parent_seq = normalize_sequence(parent_seq)
    query_seq = normalize_sequence(query_seq)
    return parent_seq[64:67] == query_seq[64:67]


def approximate_net_charge(seq):
    seq = normalize_sequence(seq)
    positive = seq.count("K") + seq.count("R") + 0.1 * seq.count("H")
    negative = seq.count("D") + seq.count("E")
    return round(positive - negative, 3)


def mutation_positions(mutations):
    positions = []
    for mutation in mutations:
        _, pos, _ = parse_mutation_token(mutation)
        positions.append(pos)
    return positions


def has_duplicate_positions(mutations):
    positions = mutation_positions(mutations)
    return len(positions) != len(set(positions))


def clean_name(name):
    name = str(name)
    name = re.sub(r"[^A-Za-z0-9_.-]+", "_", name)
    return name

single_mut_summary = single_mut_summary.copy()
single_mut_summary["mutation"] = single_mut_summary["mutation"].astype(str)

single_mut_map = (
    single_mut_summary
    .set_index("mutation")
    .to_dict(orient="index")
)

beforetop_sequences = set(beforetop_df["sequence"].map(normalize_sequence))

sfGFP = validate_protein_sequence_local("sfGFP", sfGFP)
avGFP = validate_protein_sequence_local("avGFP", avGFP)

sfGFP_net_charge = approximate_net_charge(sfGFP)

print("Stage 3 v2 input checks:")
print(f"sfGFP length: {len(sfGFP)}")
print(f"sfGFP chromophore 65-67: {sfGFP[64:67]}")
print(f"sfGFP approximate net charge: {sfGFP_net_charge}")
print(f"Excluded sequences: {len(excluded_sequences)}")
print(f"Beforetop sequences: {len(beforetop_sequences)}")
print(f"avGFP WT predicted brightness baseline from Stage 2: {pred_avGFP_WT:.4f}")

DMS_EQUIVALENT_MUTATION = {
    "F46L": "F45L",
    "H148S": "H147S",
    "N149K": "N148K",
    "N164Y": "N163Y",
    "S208L": "S207L",
    "Q69L": "Q68L"
}


def get_dms_evidence_for_mutation(sf_mutation):
    dms_key = DMS_EQUIVALENT_MUTATION.get(sf_mutation, sf_mutation)
    row = single_mut_map.get(dms_key, None)

    if row is None:
        return {
            "dms_key": dms_key,
            "has_single_observation": False,
            "observed_single_brightness_mean": np.nan,
            "ridge_coefficient": np.nan,
            "local_dms_score": 0.0
        }

    observed = row.get("observed_single_brightness_mean", np.nan)
    coef = row.get("ridge_coefficient", np.nan)

    score = 0.0

    if pd.notna(observed):
        # Нас интересует относительный сигнал около avGFP WT.
        # Слишком большие значения ограничиваем, чтобы одна мутация не доминировала.
        score += max(-0.5, min(0.8, (float(observed) - float(pred_avGFP_WT)) * 2.0))

    if pd.notna(coef):
        score += max(-0.4, min(0.4, float(coef)))

    return {
        "dms_key": dms_key,
        "has_single_observation": pd.notna(observed),
        "observed_single_brightness_mean": float(observed) if pd.notna(observed) else np.nan,
        "ridge_coefficient": float(coef) if pd.notna(coef) else np.nan,
        "local_dms_score": float(score)
    }

DMS_BRIGHT_SAFE = [
    "L220V",
    "L194M",
    "D102E",
    "L220Q",
    "Q183L",
    "A226T",
    "A226D",
    "V11L",
    "T49S",
    "Q183R"
]

LITERATURE_BRIGHTNESS = [
    "H148S"
]

NEGATIVE_SUPERCHARGE = [
    "N198D",
    "K101E",
    "K156E",
    "K166E",
    "K214E",
    "N212D"
]

FOLDING_PRIOR = [
    "N164Y",
    "N149K",
    "S208L"
]

OPTIONAL_RISK = [
    "F46L"
]

MUTATION_LIBRARY_V2 = []

for mutation in DMS_BRIGHT_SAFE:
    MUTATION_LIBRARY_V2.append({
        "mutation": mutation,
        "category": "dms_brightness_safe"
    })

for mutation in LITERATURE_BRIGHTNESS:
    MUTATION_LIBRARY_V2.append({
        "mutation": mutation,
        "category": "literature_brightness_prior"
    })

for mutation in NEGATIVE_SUPERCHARGE:
    MUTATION_LIBRARY_V2.append({
        "mutation": mutation,
        "category": "negative_supercharging"
    })

for mutation in FOLDING_PRIOR:
    MUTATION_LIBRARY_V2.append({
        "mutation": mutation,
        "category": "folding_prior"
    })

for mutation in OPTIONAL_RISK:
    MUTATION_LIBRARY_V2.append({
        "mutation": mutation,
        "category": "optional_risk"
    })

mutation_category = {
    item["mutation"]: item["category"]
    for item in MUTATION_LIBRARY_V2
}

all_mutations_v2 = [item["mutation"] for item in MUTATION_LIBRARY_V2]


print("\nChecking Stage 3 v2 mutation library on sfGFP:")

mutation_evidence_rows = []

for mutation in all_mutations_v2:
    test_seq = apply_mutations_local(sfGFP, [mutation])
    evidence = get_dms_evidence_for_mutation(mutation)

    mutation_evidence_rows.append({
        "mutation": mutation,
        "category": mutation_category[mutation],
        "dms_key": evidence["dms_key"],
        "has_single_observation": evidence["has_single_observation"],
        "observed_single_brightness_mean": evidence["observed_single_brightness_mean"],
        "ridge_coefficient": evidence["ridge_coefficient"],
        "local_dms_score": evidence["local_dms_score"]
    })

    print(
        f"OK: {mutation:6s} | category={mutation_category[mutation]:28s} "
        f"| dms_key={evidence['dms_key']:6s} | local_dms_score={evidence['local_dms_score']:.3f}"
    )

mutation_evidence_df = pd.DataFrame(mutation_evidence_rows)

mutation_evidence_path = os.path.join(OUTPUT_DIR_V2, "mutation_evidence_v2.csv")
mutation_evidence_df.to_csv(mutation_evidence_path, index=False)


def candidate_local_brightness_score(mutations):
    score = 0.0

    for mutation in mutations:
        evidence = get_dms_evidence_for_mutation(mutation)
        score += evidence["local_dms_score"]

    if "H148S" in mutations:
        score += 1.2
    if "N164Y" in mutations:
        score += 0.15
    if "F46L" in mutations:
        score -= 0.25

    return float(score)


def candidate_stability_proxy_score(seq, mutations):
    net_charge = approximate_net_charge(seq)
    charge_delta = sfGFP_net_charge - net_charge
    charge_score = np.exp(-((charge_delta - 6.0) ** 2) / (2 * 3.0 ** 2))

    folding_count = sum(1 for m in mutations if mutation_category[m] == "folding_prior")
    supercharge_count = sum(1 for m in mutations if mutation_category[m] == "negative_supercharging")

    stability_score = (
        1.20 * charge_score +
        0.25 * folding_count +
        0.12 * supercharge_count
    )

    return float(stability_score)


def candidate_risk_penalty(mutations):
    penalty = 0.0
    penalty += 0.08 * len(mutations)

    if len(mutations) > 7:
        penalty += 0.50

    terminal_mutations = 0

    for mutation in mutations:
        _, pos, _ = parse_mutation_token(mutation)
        if pos <= 10 or pos >= 221:
            terminal_mutations += 1

    if terminal_mutations > 1:
        penalty += 0.10
    if "F46L" in mutations:
        penalty += 0.15

    return float(penalty)


def candidate_total_prescore(seq, mutations):
    brightness = candidate_local_brightness_score(mutations)
    stability = candidate_stability_proxy_score(seq, mutations)
    penalty = candidate_risk_penalty(mutations)

    total = (
        0.50 * brightness +
        0.40 * stability -
        penalty
    )

    return float(total)


candidate_rows = []
seen_sequences = set()

min_mutations = 3
max_mutations = 7

for mutation_count in range(min_mutations, max_mutations + 1):
    for combo in itertools.combinations(all_mutations_v2, mutation_count):
        combo = list(combo)

        if has_duplicate_positions(combo):
            continue

        category_counts = {
            "dms_brightness_safe": sum(mutation_category[m] == "dms_brightness_safe" for m in combo),
            "literature_brightness_prior": sum(mutation_category[m] == "literature_brightness_prior" for m in combo),
            "negative_supercharging": sum(mutation_category[m] == "negative_supercharging" for m in combo),
            "folding_prior": sum(mutation_category[m] == "folding_prior" for m in combo),
            "optional_risk": sum(mutation_category[m] == "optional_risk" for m in combo)
        }

        has_brightness_basis = (
            category_counts["literature_brightness_prior"] >= 1 or
            category_counts["dms_brightness_safe"] >= 2
        )

        has_stability_basis = (
            category_counts["negative_supercharging"] >= 1 or
            category_counts["folding_prior"] >= 1
        )

        if not has_brightness_basis:
            continue

        if not has_stability_basis:
            continue

        if category_counts["negative_supercharging"] > 4:
            continue

        if category_counts["optional_risk"] > 1:
            continue

        try:
            seq = apply_mutations_local(sfGFP, combo)
            seq = validate_protein_sequence_local("candidate", seq)
        except Exception:
            continue

        if not chromophore_preserved(sfGFP, seq):
            continue

        if seq in seen_sequences:
            continue

        seen_sequences.add(seq)

        if seq in excluded_sequences:
            continue

        if seq in beforetop_sequences:
            continue

        net_charge = approximate_net_charge(seq)
        charge_delta = sfGFP_net_charge - net_charge

        if charge_delta < 0:
            continue

        if charge_delta > 12:
            continue

        brightness_score = candidate_local_brightness_score(combo)
        stability_score = candidate_stability_proxy_score(seq, combo)
        risk_penalty = candidate_risk_penalty(combo)
        total_score = candidate_total_prescore(seq, combo)

        if charge_delta < 3:
            charge_bin = "mild"
        elif charge_delta < 7:
            charge_bin = "medium"
        elif charge_delta < 10:
            charge_bin = "strong"
        else:
            charge_bin = "very_strong"

        candidate_rows.append({
            "Candidate_ID": f"CANDV2_{len(candidate_rows) + 1:05d}",
            "Sequence": seq,
            "Length": len(seq),
            "Mutations": ":".join(combo),
            "Mutation_Count": len(combo),
            "Approx_Net_Charge": net_charge,
            "Charge_Delta_More_Negative_vs_sfGFP": charge_delta,
            "Charge_Bin": charge_bin,
            "Has_H148S": "H148S" in combo,
            "DMS_Brightness_Safe_Count": category_counts["dms_brightness_safe"],
            "Supercharge_Count": category_counts["negative_supercharging"],
            "Folding_Count": category_counts["folding_prior"],
            "Optional_Risk_Count": category_counts["optional_risk"],
            "Local_Brightness_Evidence_Score": brightness_score,
            "Stability_Proxy_Score": stability_score,
            "Risk_Penalty": risk_penalty,
            "Pre_ColabFold_MultiObjective_Score": total_score,
            "Chromophore_65_67": seq[64:67],
            "Chromophore_Preserved": True,
            "In_Exclusion_List": False,
            "Exact_Match_BeforeTopSeqs": False
        })

df_candidates_v2 = pd.DataFrame(candidate_rows)

if df_candidates_v2.empty:
    raise ValueError("Stage 3 v2 generated no candidates.")

df_candidates_v2 = df_candidates_v2.sort_values(
    [
        "Pre_ColabFold_MultiObjective_Score",
        "Local_Brightness_Evidence_Score",
        "Stability_Proxy_Score"
    ],
    ascending=False
).reset_index(drop=True)

df_candidates_v2["Pre_Rank"] = np.arange(1, len(df_candidates_v2) + 1)

print("\nStage 3 v2 candidates after hard filters:")
print(df_candidates_v2.shape[0])

def select_family(df, condition, n, family_name):
    subset = df[condition].copy()
    subset = subset.sort_values(
        [
            "Pre_ColabFold_MultiObjective_Score",
            "Local_Brightness_Evidence_Score",
            "Stability_Proxy_Score"
        ],
        ascending=False
    ).head(n)

    subset["Design_Family"] = family_name
    return subset


selected_blocks = []

selected_blocks.append(
    select_family(
        df_candidates_v2,
        (df_candidates_v2["Mutation_Count"].between(3, 4)) &
        (df_candidates_v2["Charge_Delta_More_Negative_vs_sfGFP"] <= 3.5) &
        (df_candidates_v2["Has_H148S"] == True),
        5,
        "conservative_H148S_mild_charge"
    )
)

selected_blocks.append(
    select_family(
        df_candidates_v2,
        (df_candidates_v2["Mutation_Count"].between(4, 5)) &
        (df_candidates_v2["Charge_Delta_More_Negative_vs_sfGFP"].between(3.0, 6.5)) &
        (df_candidates_v2["Has_H148S"] == True),
        6,
        "balanced_H148S_medium_charge"
    )
)

selected_blocks.append(
    select_family(
        df_candidates_v2,
        (df_candidates_v2["Mutation_Count"].between(5, 6)) &
        (df_candidates_v2["Charge_Delta_More_Negative_vs_sfGFP"].between(5.0, 8.5)) &
        (df_candidates_v2["Has_H148S"] == True),
        6,
        "balanced_H148S_stronger_charge"
    )
)

selected_blocks.append(
    select_family(
        df_candidates_v2,
        (df_candidates_v2["Mutation_Count"].between(6, 7)) &
        (df_candidates_v2["Charge_Delta_More_Negative_vs_sfGFP"].between(8.0, 12.0)) &
        (df_candidates_v2["Has_H148S"] == True),
        4,
        "thermal_supercharged_H148S"
    )
)

selected_blocks.append(
    select_family(
        df_candidates_v2,
        (df_candidates_v2["Mutation_Count"].between(4, 6)) &
        (df_candidates_v2["Charge_Delta_More_Negative_vs_sfGFP"].between(2.0, 8.0)) &
        (df_candidates_v2["Has_H148S"] == False),
        3,
        "backup_without_H148S"
    )
)

df_top24_v2 = pd.concat(selected_blocks, axis=0)
df_top24_v2 = df_top24_v2.drop_duplicates("Sequence").reset_index(drop=True)

if df_top24_v2.shape[0] < 24:
    already = set(df_top24_v2["Sequence"])

    filler = df_candidates_v2[
        ~df_candidates_v2["Sequence"].isin(already)
    ].head(24 - df_top24_v2.shape[0]).copy()

    filler["Design_Family"] = "global_score_filler"

    df_top24_v2 = pd.concat([df_top24_v2, filler], axis=0)

df_top24_v2 = df_top24_v2.head(24).reset_index(drop=True)

df_top24_v2["ColabFold_Query_ID"] = [
    f"Query_{i:02d}_{row.Candidate_ID}"
    for i, row in enumerate(df_top24_v2.itertuples(), start=1)
]


all_candidates_v2_path = os.path.join(
    OUTPUT_DIR_V2,
    "all_generated_candidates_ranked_v2.csv"
)

top24_v2_path = os.path.join(
    OUTPUT_DIR_V2,
    "top24_for_colabfold_v2.csv"
)

df_candidates_v2.to_csv(all_candidates_v2_path, index=False)
df_top24_v2.to_csv(top24_v2_path, index=False)


print("\nTop 24 candidates selected for ColabFold — Stage 3 v2:")
display(
    df_top24_v2[
        [
            "ColabFold_Query_ID",
            "Candidate_ID",
            "Design_Family",
            "Mutations",
            "Mutation_Count",
            "Approx_Net_Charge",
            "Charge_Delta_More_Negative_vs_sfGFP",
            "Charge_Bin",
            "Has_H148S",
            "DMS_Brightness_Safe_Count",
            "Supercharge_Count",
            "Folding_Count",
            "Local_Brightness_Evidence_Score",
            "Stability_Proxy_Score",
            "Risk_Penalty",
            "Pre_ColabFold_MultiObjective_Score"
        ]
    ]
)


with open(os.path.join(COLABFOLD_FASTA_DIR_V2, "sfGFP_WT.fasta"), "w", encoding="utf-8") as handle:
    handle.write(">sfGFP_WT\n")
    handle.write(sfGFP + "\n")

for _, row in df_top24_v2.iterrows():
    query_id = clean_name(row["ColabFold_Query_ID"])
    seq = row["Sequence"]

    fasta_path = os.path.join(COLABFOLD_FASTA_DIR_V2, f"{query_id}.fasta")

    with open(fasta_path, "w", encoding="utf-8") as handle:
        handle.write(f">{query_id}\n")
        handle.write(seq + "\n")

print("\nFASTA files created for Stage 3 v2 ColabFold:")
for filename in sorted(os.listdir(COLABFOLD_FASTA_DIR_V2)):
    print(filename)

stage3_v2_metadata = {
    "timestamp": datetime.now().isoformat(timespec="seconds"),
    "parent_scaffold": "sfGFP",
    "sfGFP_length": len(sfGFP),
    "sfGFP_chromophore_65_67": sfGFP[64:67],
    "sfGFP_approx_net_charge": sfGFP_net_charge,
    "reason_for_stage3_v2": (
        "Stage 3 v1 full-sequence avGFP-transfer brightness prediction saturated "
        "and assigned the same brightness value to all sfGFP candidates. "
        "Stage 3 v2 therefore uses mutation-level DMS evidence, H148S literature prior, "
        "charge/stability proxy, and explicit diversity constraints."
    ),
    "mutation_library_v2": MUTATION_LIBRARY_V2,
    "generated_candidates_after_filters": int(df_candidates_v2.shape[0]),
    "selected_for_colabfold": int(df_top24_v2.shape[0]),
    "hard_filters": [
        "length 220-250 aa",
        "starts with M",
        "standard amino acids only",
        "chromophore 65-67 preserved",
        "not exact match in Exclusion_List.csv",
        "not exact match in beforetopseqs",
        "Q69L excluded due to negative DMS-equivalent Q68L brightness signal"
    ],
    "design_families": list(df_top24_v2["Design_Family"].unique())
}

metadata_v2_path = os.path.join(
    OUTPUT_DIR_V2,
    "stage3_v2_metadata.json"
)

with open(metadata_v2_path, "w", encoding="utf-8") as handle:
    json.dump(stage3_v2_metadata, handle, indent=2, ensure_ascii=False)


zip_base_v2 = os.path.join(
    OUTPUT_DIR_V2,
    "colabfold_top24_fasta_v2"
)

zip_path_v2 = shutil.make_archive(
    zip_base_v2,
    "zip",
    COLABFOLD_FASTA_DIR_V2
)


print("\nSaved files:")
print(all_candidates_v2_path)
print(top24_v2_path)
print(mutation_evidence_path)
print(metadata_v2_path)
print(zip_path_v2)


files.download(all_candidates_v2_path)
files.download(top24_v2_path)
files.download(mutation_evidence_path)
files.download(metadata_v2_path)
files.download(zip_path_v2)

